services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - db
    networks:
      - leads-scheduler-network

  web:
    image: nginx:latest
    restart: on-failure
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
#      - "4000:4000"
      - "8080:80"
      - "443:443"
    depends_on:
      - app
      - browser
    networks:
      - leads-scheduler-network

  browser:
    container_name: browser
    build:
      context: ./browser
      dockerfile: ./Dockerfile
    working_dir: /app
    restart: unless-stopped
    command: "npm install && npm start"
    volumes:
      - ./browser:/app
    ports:
      - "3000:4000"
    networks:
      - leads-scheduler-network

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - leads-scheduler-network

networks:
  leads-scheduler-network:
    driver: bridge

volumes:
  dbdata:
