services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - db
    networks:
      private_net:
        ipv4_address: 172.28.1.1

  web:
    image: nginx:latest
    restart: on-failure
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "81:80"
    depends_on:
      - app
      - browser
    networks:
      private_net:
        ipv4_address: 172.28.1.2

  browser:
    container_name: browser
    restart: always
    build:
      context: ./browser
      dockerfile: ./Dockerfile
    working_dir: /app
    volumes:
      - ./browser:/app
    ports:
      - "4000:4000"
    networks:
      private_net:
        ipv4_address: 172.28.1.3

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      private_net:
        ipv4_address: 172.28.1.4

networks:
  private_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
volumes:
  dbdata:
